const jokes = [
  "Why was the computer cold? Because it left its Windows open.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do Java developers wear glasses? Because they can't C#",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the coffee file a police report? It got mugged!",
  "Why did the math book look so mad? Because it had too many problems.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the cookie go to the doctor? Because it felt crumbly.",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the cookie go to the doctor? Because it felt crumbly.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "Why did the computer go to the doctor? It had a virus!",
  "Why did the boy bring duct tape to the picnic? He wanted to keep the flies together!",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why did the computer cold? Because it left its Windows open.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the coffee file a police report? It got mugged!",
  "Why did the math book look so mad? Because it had too many problems.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the cookie go to the doctor? Because it felt crumbly.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "Why did the computer go to the doctor? It had a virus!",
  "Why did the boy bring duct tape to the picnic? He wanted to keep the flies together!",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open!",
  "Why do programmers always miss their loved ones? Because they cannot debug their relationships.",
  "Why do programmers always forget to sleep? Because they C code in their dreams.",
  "Why do programmers prefer dark mode? Light attracts bugs.",
  "Why did the programmer quit his job? He didn’t get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why did the JavaScript developer wear glasses? Because he didn’t C#!",
  "Why did the programmer call his boss “boss”? Because that was the name of his GUI.",
  "Why did the programmer quit his job? He couldn’t get a raise, he only knew how to do one thing: ++!",
  "Why did the programmer always break up with his girlfriend? She asked him to make a GUI.",
  "Why do programmers always have to have caffeine? Because without it, they’re just code.",
  "Why did the programmer go bankrupt? He lost all his source code!",
  "Why was the programmer always calm? He had a try-catch block around everything.",
  "Why did the programmer quit his job? He was tired of constantly debugging his code.",
  "Why did the programmer always wear sunglasses? He was constantly in the binary world.",
  "Why did the programmer always bring a ladder to work? He needed to reach the top of the stack.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why do programmers always miss their loved ones? Because they cannot debug their relationships.",
  "Why did the programmer always take his laptop to the bar? He wanted to catch a few bytes.",
  "Why did the programmer cross the road? To get to the software development shop.",
  "Why did the programmer always carry an umbrella? To catch his exceptions!",
  "Why did the programmer always wear a suit? He wanted to look binary!",
  "Why did the programmer always bring a map to work? He wanted to find the null pointer!",
  "Why did the programmer always wear a watch? He wanted to keep track of his time complexity!",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why did the programmer always carry a red pen? He wanted to debug on paper!",
  "Why did the programmer always wear a hat? He wanted to keep his head in the cloud!",
  "Why did the programmer always bring a calculator to work? He wanted to do some bit shifting!",
  "Why did the programmer always carry a water bottle? He wanted to stay hydrated while debugging!",
  "Why did the programmer always wear a backpack? He wanted to carry all of his bits and bytes!",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why did the programmer always wear a hoodie? He wanted to keep his code warm!",
  "Why did the programmer always carry a laptop? He wanted to write code on the go!",
  "Why did the programmer always wear headphones? He wanted to listen to his code!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the coffee file a police report? It got mugged!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Why did the hipster burn his tongue? He drank his coffee before it was cool!",
  "Why did the math book look so mad? Because it had too many problems!",
  "Why did the computer go to the doctor? Because it had a virus!",
  "Why did the chicken cross the playground? To get to the other slide!",
  "Why did the penguin cross the road? To show everyone it could fly!",
  "Why did the cookie go to the doctor? Because it felt crumbly!",
  "Why did the pirate cross the ocean? To get to the other tide!",
  "Why did the camel put his nose in the tent? Because he wanted to see the nomad!",
  "Why did the tree go to the bar? To get some root beer!",
  "Why did the snake buy a pair of sunglasses? To keep from hissing!",
  "Why did the fox cross the road? To show the chicken it could be done!",
  "Why did the cat put the mouse in the blender? To see if it would purr!",
  "Why did the bee cross the road? To get to the flower shop!",
  "Why did the horse go to the bar? To get a horseshoe!",
  "Why did the pig join the gym? To get in shape!",
  "Why did the skeleton cross the road? To get to the body shop!",
  "Why did the ant go to the bank? To get a loan!",
  "Why did the elephant go to the beach? To get a tan!",
  "Why did the bird go to the bar? To get a drink!",
  "Why did the frog call the doctor? He had a jump in his throat!",
  "Why did the wolf go to the salon? To get a howl cut!",
  "Why did the duck go to the doctor? Because it had the quacks!",
  "Why did the monkey go to the bar? To get a banana daiquiri!",
  "Why did the bear go to the bar? To get a honey martini!",
  "Why did the deer go to the bar? To get a buck!",
  "Why did the squirrel go to the bar? To get a nut!",
  "Why did the dog go to the bar? To get a paw-tini!",
  "Why did the lion go to the bar? To get a mane event!",
  "Why did the giraffe go to the bar? To get a neck-up!",
  "Why did the zebra go to the bar? To get a stripe!",
  "Why did the kangaroo go to the bar? To get a jump start!",
  "Why did the mouse go to the bar? To get a mouse trap!",
  "Why did the skunk go to the bar? To get a scent!",
  "Why did the alligator go to the bar? To get a bite!"
  ]

let n = Math.floor(Math.random() * (jokes.length));
let x = jokes[n];
let elem = document.getElementsByClassName("joke")[0];
elem.innerHTML = x;