const jokes = [
  "Why was the computer cold? Because it left its Windows open.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do Java developers wear glasses? Because they can't C#",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the coffee file a police report? It got mugged!",
  "Why did the math book look so mad? Because it had too many problems.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the cookie go to the doctor? Because it felt crumbly.",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the cookie go to the doctor? Because it felt crumbly.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "Why did the computer go to the doctor? It had a virus!",
  "Why did the boy bring duct tape to the picnic? He wanted to keep the flies together!",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why did the computer cold? Because it left its Windows open.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the coffee file a police report? It got mugged!",
  "Why did the math book look so mad? Because it had too many problems.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the cookie go to the doctor? Because it felt crumbly.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "Why did the computer go to the doctor? It had a virus!",
  "Why did the boy bring duct tape to the picnic? He wanted to keep the flies together!",
  "Why did the programmer quit his job? He didn't get arrays.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "Why was the computer cold? Because it left its Windows open.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't scientists trust atoms? Because they make up everything." ]

let n = Math.floor(Math.random() * (jokes.length)) + 1;
let x = jokes[n];
let elem = document.getElementsByClassName("joke")[0];
elem.innerHTML = x;